### ISSUE TITLE
Move Docker configuration to a seperate file

### ISSUE THREAD

**Issue by chrsi** [meinsiedler/NoSQLExplorer#10]
Currently the Docker configuration is written in the app.config.
This should be moved into a seperate file, to prevent those "sensitive lines" in the app.config to be checked in.
This file can then be added to the .gitignore list

**Comment by mdi1984** [comment]
what about [this](http://stackoverflow.com/questions/18276951/how-do-i-stop-git-from-tracking-any-changes-to-a-file-from-this-commit-forward) ?

**Comment by meinsiedler** [comment]
Completely ignoring a configuration file would be a bad idea, because in that case we would never have a valid and complete configuration checked into the repository. Then we would always be dependent on the fact that every developer first checks out the repository and then creates all the missing configuration files locally.

Therefore, the better approach would be to check in a configuration file with dummy values and then mark the files with `--assumed-unchanged` to prevent unintended check ins (as in @mdi1984's provided link).

Unfortunatelly, `--assumed-unchanged` is a *local* git setting which is not pushed to the repository. This means that everyone has to configure it accordingly.

**Comment by chrsi** [comment]
Looks more like a mix of both solutions is needed. Since "--assumed-unchanged"ing the whole app.config, would cause every further update to be ignored.
Currently I extracted the settings to a seperate config file. All that has to be done right now is to check in default values for those and mark them with that flag.

**Comment by meinsiedler** [comment]
@chrsi Is there any update on this? I saw your changes in the other branch. This is OK for me, except that we shouldn't add the .config files to the .gitignore file as mentioned above.

When we merge your branch I also considered extracting all Twitter configurations to a separate config section which then can be also extracted to a separate file. With that approach we would then have a consistent handling of configuration for all parts of the application.
